
liip_imagine:

    filter_sets:
        cache: ~

        # the name of the "filter set"
        thumb_s:

            # adjust the image quality to 75%
            quality: 100

            # list of transformations to apply (the "filters")
            filters:

                # create a thumbnail: set size to 120x90 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail:
                    size: [130, 98]
                    mode: outbound
                    allow_upscale: true
