old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
            lazy: true
    producers:
        # use 'old_sound_rabbit_mq.import_producer' service to send data.
        send_message:
            connection:       default
            exchange_options: { name: 'import', type: direct }
    consumers:
        receive_message:
            connection:       default
            exchange_options: { name: 'import', type: direct }
            queue_options:    { name: 'import'}
            callback:         App\Consumer\RecieveConsumer
