webpack_encore:
    # The path where Encore is building the assets.
    # This should match Encore.setOutputPath() in webpack.config.js.
    output_path: '%kernel.project_dir%/public/build/app_build'
    builds:
        appConfig: '%kernel.project_dir%/public/build/app_build'
        adminConfig: '%kernel.project_dir%/public/build/admin_build'
