version: '3'
services:
    mysql:
        image: mysql:5.7
        volumes:
            - ./tests/db:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=test_db
        ports:
            - 3306:3306
    rabbitmq:
        image: rabbitmq
        ports:
            - 5672:5672        
    app:
        build:
            context: .
        links:
            - mysql
        depends_on:
            - mysql
        volumes:
            - .:/var/www/:cached
            - /var/www/vendor/
            - /var/www/node_modules
        command: bin/console server:run 0.0.0.0:80
        ports:
            - 8000:80
